---
nats_servers:

  - nats://nats:SharedSecret@NatsAddress:4222


dea_ruby: /usr/bin/ruby

pid_filename: /var/vcap/sys/run/dea_next/dea_next.pid

base_dir: /var/vcap/data/dea_next

warden_socket: /var/vcap/data/warden/warden.sock

evacuation_bail_out_time_in_seconds: 115
default_health_check_timeout: 60
crash_lifetime_secs: 3600

directory_server:
  protocol: 'http'
  v1_port: 12345
  v2_port: 34567
  file_api_port: 23456
  streaming_timeout: 
  logging:
    file: /var/vcap/sys/log/dea_next/dir_server.log
    
    syslog: vcap.directory_server
    
    level: debug

domain: CloudfoundryDomain

logging:
  file: /var/vcap/sys/log/dea_next/dea_next.log
  level: debug
  
  syslog: vcap.dea_next
  


loggregator:
  router: RouterAddress:3456
  shared_secret: SharedSecret


index: 0

intervals:
  heartbeat: 10
  advertise: 5

resources:
  memory_mb: 4096
  memory_overcommit_factor: 1
  disk_mb: 16384
  disk_overcommit_factor: 1

bind_mounts:
- src_path: /var/vcap/packages/buildpack_cache

staging:
  enabled: true
  max_staging_duration: 900
  memory_limit_mb: 1024
  disk_limit_mb: 2048
  cpu_limit_shares: 512
  disk_inode_limit: 200000
  environment:
    BUILDPACK_CACHE: "/var/vcap/packages/buildpack_cache"

instance:
  cpu_limit_shares: 256
  disk_inode_limit: 200000
  memory_to_cpu_share_ratio: 8
  max_cpu_share_limit: 256
  min_cpu_share_limit: 1

stacks: ["lucid64"]
placement_properties:
  zone: default
